- name: Create a cluster of full cloned containers
  hosts: proxmox
  gather_facts: false

  vars_files:
    - "../group_vars/{{ env }}.yml"

  tasks:
    - name: Include task to create each LXC container
      include_tasks: tasks/create_one_lxc.yml
      loop: "{{ range(0, count) | list }}"
      loop_control:
        index_var: index
      vars:
        index: "{{ index }}"